name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  ECR_REPO: public.ecr.aws/k1n1h4h4
  
jobs:
  build:
    name: release
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Dockerx
        uses: docker/setup-buildx-action@v1
      - name: Build and push container images
        uses: docker/build-push-action@v2
        with:
          build-args: |
            pkg_version=${{ steps.tag.outputs.tag }}
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.TAG_BASE }}:latest
            ${{ env.TAG_BASE }}:${{steps.tag.outputs.tag}}
          push: true
