name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

  
jobs:
  build:
    name: release
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: koteswarp
          password: xGr7+H~=9.CYtvJ
      - name: Setup Dockerx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            pkg_version=${{ steps.tag.outputs.tag }}
          context: ./
          file: ./Dockerfile
          push: true
          tags: koteswarp/simplewhale:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
